version: "3.8"
services:
  user-service:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      # DB_USER: postgres
      # DB_HOST: db
      # DB_NAME: users
      # DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - jpeg

  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - jpeg
    restart: always

volumes:
  db_data:

networks:
  jpeg:
    external: true