apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: google/cloud-sdk:slim
            command:
            - /bin/bash
            - -c
            - |
              apt-get update && apt-get install -y postgresql-client gzip
              gcloud auth activate-service-account --key-file=/var/secrets/google/key.json
              export PGPASSWORD="$POSTGRES_PASSWORD"
              TIMESTAMP=$(date +%Y%m%d-%H%M)
              echo "Backing up database at $TIMESTAMP"
              pg_dump -h db-service -U "$POSTGRES_USER" -d users | gzip > /tmp/backup-$TIMESTAMP.sql.gz
              echo "Uploading backup to GCS..."
              gsutil cp /tmp/backup-$TIMESTAMP.sql.gz gs://my-postgres-backups/
              echo "Backup complete"
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            volumeMounts:
            - name: gcp-sa
              mountPath: /var/secrets/google
              readOnly: true
          volumes:
          - name: gcp-sa
            secret:
              secretName: gcs-service-account
